server:
  port: 7003
app:
  mail: rajamanikandanreg32@gmail.com
  baseUrl: http://localhost:7003/api
  otpLen: 6
  otpExpire: 5
  auth:
    urls: /api/validation,/api/auth
  jwt:
    secret-key: "$2a$12$L1E2yksxbSr9gVwb/WZJc.9w5Nc5beROD3nL8ZbG8R36ENhk9HbOu"
    expire: 1
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/milkDb?createDatabaseIfNotExist=true
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: springbootcommon@gmail.com
    password: paxqexbobtfsysir
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
